require:
 - rubocop-performance
 - rubocop-rake
 - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - '*.gemspec'

RSpec/MultipleExpectations:
  Max: 5

RSpec/ExampleLength:
  Max: 20

Lint/MissingSuper:
  Enabled: false
