inherit_from: .rubocop_todo.yml

plugins:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable

Style/Documentation:
  Exclude:
    - 'lib/pgchief.rb'
    - 'spec/**/*.rb'

Metrics/AbcSize:
  Exclude:
    - 'lib/pgchief/config.rb'

Metrics/MethodLength:
  Exclude:
    - 'lib/pgchief/config.rb'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'lib/pgchief/config.rb'
