# Connection string to superuser account at your PG instance
pgurl = "postgresql://localhost:5432"

# Directory where db backups will be placed
backup_dir = "~/.config/pgchief/backups"

# ** OPTIONAL **

# Location of saved database connection strings
# credentials_file = "~/.config/pgchief/credentials"

# S3 config - if present, will back up to S3 instead of local filesystem
# s3_key = ""
# s3_secret = ""
# s3_region = "us-east-1"
# s3_objects_path = "s3://bucket-name/database-backups/"
