#!/usr/bin/env ruby

# frozen_string_literal: true

libdir = "#{__dir__}/../lib"
$LOAD_PATH.unshift(libdir) unless $LOAD_PATH.include?(libdir)

require 'pgchief'

cli = Pgchief::Cli.new
cli.parse(ARGV)
cli.run
